import Layout from '../components/Layout';
import Link from 'next/link';

const warnings = [
  {
    icon: '⚠️',
    title: 'Educational Purpose Only',
    text: 'The tree identification results provided by TreeIdentifier are intended for educational and informational purposes only. They should not be relied upon for professional, medical, legal, or commercial decisions.',
  },
  {
    icon: '🌿',
    title: 'Not a Substitute for Expert Advice',
    text: 'Always consult a certified arborist, botanist, or forestry professional for decisions involving tree care, removal, health assessment, or species-specific guidance in sensitive ecological or commercial contexts.',
  },
  {
    icon: '🍄',
    title: 'Foraging Warning',
    text: 'NEVER use AI tree or plant identification to determine if any plant, berry, mushroom, or other natural material is safe to eat or use medicinally. Misidentification can be fatal. Consult qualified experts before consuming wild plants.',
  },
  {
    icon: '🔬',
    title: 'Accuracy Limitations',
    text: 'While our AI achieves high accuracy, no identification system is perfect. Results may vary based on photo quality, lighting, angle, unusual specimens, regional varieties, or hybrid species. Always verify important identifications through multiple sources.',
  },
];

const sections = [
  {
    title: 'Accuracy Disclaimer',
    content: 'TreeIdentifier uses artificial intelligence to analyze images and provide tree species identification. While we strive for the highest possible accuracy, we cannot guarantee that every identification will be correct. Our AI system is continuously improving, but it has inherent limitations based on image quality, species rarity, regional variations, and the complexity of botanical identification. Confidence levels provided are estimates, not guarantees.',
  },
  {
    title: 'No Professional Advice',
    content: 'The information provided by TreeIdentifier, including species identification, care tips, ecological information, and cultivation guidance, does not constitute professional arboricultural, horticultural, ecological, or legal advice. For matters involving tree removal, structural assessment, disease diagnosis, or any application with significant practical consequences, please engage a qualified professional.',
  },
  {
    title: 'Safety and Health',
    content: 'TreeIdentifier expressly disclaims any responsibility for adverse effects resulting from the use of our identification tool in contexts involving food safety, allergies, or medicinal applications. Some trees and plants are highly toxic to humans and animals. Do not rely on our identification results to determine if a plant is safe for consumption or contact without expert verification.',
  },
  {
    title: 'Image Privacy',
    content: 'By uploading images to TreeIdentifier, you confirm that you have the right to share those images and that they do not contain sensitive personal information. Images are processed for identification only and are not stored. However, we cannot be held responsible for any inadvertent disclosure of information contained within uploaded images.',
  },
  {
    title: 'Third-Party Links',
    content: 'Our website may contain links to third-party websites and resources for additional information. These links are provided for convenience only. We have no control over and accept no responsibility for the content, accuracy, or availability of external sites. The inclusion of any link does not imply endorsement by TreeIdentifier.',
  },
  {
    title: 'Limitation of Liability',
    content: 'To the maximum extent permitted by applicable law, TreeIdentifier, its operators, developers, and contributors shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of our service, reliance on our identification results, or any errors or omissions in our AI outputs. Your use of TreeIdentifier is entirely at your own risk.',
  },
  {
    title: 'Intellectual Property',
    content: 'Tree identification results generated by our AI are provided for personal, non-commercial use. The underlying technology, database, and website design are proprietary. You may not reproduce, distribute, or create derivative works from our content without express written permission.',
  },
  {
    title: 'Service Availability',
    content: 'TreeIdentifier is provided "as is" without warranties of any kind. We do not guarantee uninterrupted, error-free service. We reserve the right to modify, suspend, or discontinue the service at any time without notice. We shall not be liable for any downtime or loss of access.',
  },
];

export default function DisclaimerPage() {
  return (
    <Layout
      title="Disclaimer"
      description="Important disclaimer about TreeIdentifier's AI tree identification service. Read before using our tool for critical decisions."
      canonical="https://treeidentifier.com/disclaimer"
    >
      {/* Hero — amber/dark tones for seriousness */}
      <section className="relative min-h-[40vh] flex items-center overflow-hidden">
        <div
          className="absolute inset-0 bg-cover bg-center"
          style={{ backgroundImage: 'url(https://images.unsplash.com/photo-1448375240586-882707db888b?w=1920&q=80&auto=format&fit=crop)' }}
        />
        <div className="page-hero-disclaimer absolute inset-0 opacity-90" />
        <div className="relative max-w-5xl mx-auto px-4 sm:px-6 pt-28 pb-16 text-center w-full">
          <div className="inline-block bg-white/10 border border-white/20 text-amber-200 rounded-full px-4 py-1.5 text-sm mb-6">
            ⚖️ Important Information
          </div>
          <h1 className="text-5xl sm:text-6xl font-black text-white mb-4" style={{ fontFamily: 'Playfair Display, serif' }}>
            <span className="text-amber-300">Disclaimer</span>
          </h1>
          <p className="text-amber-100 text-base max-w-xl mx-auto">
            Please read this disclaimer carefully before using TreeIdentifier. Last updated: June 2025.
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="py-20 bg-cream">
        <div className="max-w-4xl mx-auto px-4 sm:px-6">
          {/* Critical warnings */}
          <div className="grid sm:grid-cols-2 gap-4 mb-14">
            {warnings.map(({ icon, title, text }) => (
              <div key={title} className="bg-amber-50 border border-amber-200 rounded-2xl p-5 flex items-start gap-4">
                <span className="text-3xl flex-shrink-0">{icon}</span>
                <div>
                  <h3 className="text-amber-900 font-bold text-sm mb-1.5">{title}</h3>
                  <p className="text-amber-800 text-xs leading-relaxed">{text}</p>
                </div>
              </div>
            ))}
          </div>

          {/* Detailed sections */}
          <div className="space-y-6">
            {sections.map((section, i) => (
              <div key={section.title} className="bg-white rounded-3xl shadow-sm border border-gray-100 overflow-hidden">
                <div className="px-7 py-5 border-b border-gray-100 flex items-center gap-3"
                  style={{ background: 'linear-gradient(to right, rgba(139,90,0,0.05), transparent)' }}>
                  <span className="w-7 h-7 rounded-full bg-amber-100 text-amber-700 text-xs font-bold flex items-center justify-center flex-shrink-0">
                    {String(i + 1).padStart(2, '0')}
                  </span>
                  <h2 className="text-gray-900 font-bold text-lg" style={{ fontFamily: 'Playfair Display, serif' }}>{section.title}</h2>
                </div>
                <div className="px-7 py-5">
                  <p className="text-gray-600 text-sm leading-relaxed">{section.content}</p>
                </div>
              </div>
            ))}
          </div>

          {/* Agreement box */}
          <div className="mt-12 bg-forest-50 rounded-3xl p-8 border border-forest-100">
            <h2 className="text-2xl font-black text-gray-900 mb-3" style={{ fontFamily: 'Playfair Display, serif' }}>
              By Using TreeIdentifier, You Agree
            </h2>
            <p className="text-gray-500 text-sm leading-relaxed mb-6">
              Your continued use of TreeIdentifier constitutes acceptance of this Disclaimer in full. If you do not agree with any part of this disclaimer, please discontinue use of the service immediately. For questions about this disclaimer, please contact us.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <Link href="/tree-identifier" className="btn-forest px-6 py-3 rounded-full font-semibold text-sm text-center">
                I Understand — Use Tool →
              </Link>
              <Link href="/contact" className="border-2 border-forest-300 text-forest-700 px-6 py-3 rounded-full font-semibold text-sm text-center hover:bg-forest-50 transition-colors">
                Contact Us
              </Link>
              <Link href="/privacy-policy" className="border-2 border-gray-200 text-gray-500 px-6 py-3 rounded-full font-semibold text-sm text-center hover:bg-gray-50 transition-colors">
                Privacy Policy
              </Link>
            </div>
          </div>
        </div>
      </section>
    </Layout>
  );
}
